# Generated by Django 6.0.3 on 2026-03-14 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='idx_messages_conversation',
            old_name='idx_messages_conversation_created',
        ),
    ]
