# Generated by Django 6.0.3 on 2026-03-14 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('hidden', 'Hidden')], default='public', max_length=10)),
                ('match_visibility', models.CharField(choices=[('everyone', 'Everyone'), ('friends_only', 'Friends Only'), ('me_only', 'Me Only')], default='everyone', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_preferences', to='auths.user', verbose_name='privacy preference owner')),
            ],
        ),
    ]
