# version: '3.8'

services:
# # Uncomment to run django within docker
#   web:
#     build: .
#     command: python /code/manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/code
#     ports:
#       - 8000:8000
#     depends_on:
#       - db


  # db:
  #   image: postgres:14
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - "POSTGRES_HOST_AUTH_METHOD=trust"

  db:
    restart: always
    image: postgres:16
    container_name: look-like-me-postgres #you can change this
    environment:
      - POSTGRES_USER=backend_dev
      - POSTGRES_PASSWORD=RvNt5Yjzhg08Ha7o
      - POSTGRES_DB=look_like_me_db
      # - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - postgres_data:/var/lib/postgresql

  # pgadmin:
  #     image: dpage/pgadmin4
  #     container_name: demo-pgadmin #you can change this
  #     depends_on:
  #       - db
  #     ports:
  #       - "5051:80"
  #     environment:
  #       PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #       PGADMIN_DEFAULT_PASSWORD: root
  #     restart: always

volumes:
  postgres_data:
