"""
Django settings for Look_Like_Me_Project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import os
from dotenv import load_dotenv

from datetime import timedelta

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/' # url for serving
MEDIA_ROOT = BASE_DIR / 'media' # path for physical storage

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@5xtrpsf3fkbrv$%jkf3%7#(p(@iy=sg6mx!fzpn3&tg7n*2-^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    # defaults
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # APIs (DRF)
    'django_extensions',
    'rest_framework',
    'django_filters',

    # Registration and authentication
    # 'rest_framework.authtoken',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    # 'rest_framework_simplejwt',
    # 'rest_framework_simplejwt.token_blacklist',  # For logout

    'knox',

    # Project apps
    'auths',
    'matches',
    'relations',
    'chats',
    'preferences',
]

AUTH_USER_MODEL = 'auths.User' # replaces the default User model with our custom one


MIDDLEWARE = [
    # defaults
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # AUTHENTICATION
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
        # DATABASES = {
        #     "default": {
        #         "ENGINE": "django.db.backends.postgresql",
        #         # 'ENGINE': 'django_postgres_extensions.backends.postgresql',
        #         "NAME": "look_like_me_db",
        #         "USER": "backend_dev",
        #         "PASSWORD": "RvNt5Yjzhg08Ha7o",
        #         "HOST": "localhost", #"db",  # set in docker-compose.yml
        #         "PORT": 5432,  # default postgres port
        #     }
        # }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# ACCESS TOKEN CRYPTION SETTINGS
# FROM: https://dev.to/jenchen/django-rest-framework-with-simple-jwt-json-web-token-steps-on-how-to-sign-and-verify-using-the-192b

SIGNING_KEY = os.getenv('SIGNING_KEY').replace("\\n", "\n")
VERIFYING_KEY = os.getenv('VERIFYING_KEY').replace("\\n", "\n")

SIMPLE_JWT = {

    "ALGORITHM": "RS256",
    "SIGNING_KEY": SIGNING_KEY,
    "VERIFYING_KEY": VERIFYING_KEY,

}

# USER REGISTRATION & EMAIL CONFIRMATION & AUTHENTICATION SETTINGS
# FROM: https://medium.com/@michal.drozdze/django-rest-framework-jwt-authentication-sign-up-api-with-email-confirmation-0cfc6054ce8e

# django.contrib.sites
SITE_ID = 1 # what is this for? needed for allauth, which is needed for registration and email confirmation

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly"
    ],
    # Pagination allows to control how many objects per page are returned
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,

     'DEFAULT_AUTHENTICATION_CLASSES': [
         'knox.auth.TokenAuthentication',
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
        'django.contrib.auth.backends.ModelBackend', #Default authentication backend, needed for admin
     ]
}

# ALLAUTH SETTINGS
ACCOUNT_EMAIL_VERIFICATION = "mandatory" # Require email confirmation
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1 # Confirmation link expires in 1 day
LOGIN_URL = "/auths/login/"  # Path users will be redirected to after email verification

ACCOUNT_LOGIN_METHODS = {"email"}  # Use Email / Password authentication
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*'] # Fields marked with an asterisk (e.g. 'username*') are required
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
# Changed based on these WARNINGS:
    # ?: settings.ACCOUNT_AUTHENTICATION_METHOD is deprecated, use: settings.ACCOUNT_LOGIN_METHODS = {'email'}
    # ?: settings.ACCOUNT_EMAIL_REQUIRED is deprecated, use: settings.ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
    # ?: settings.ACCOUNT_USERNAME_REQUIRED is deprecated, use: settings.ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']


# dj-rest-auth
REST_AUTH = {
    "REGISTER_SERIALIZER": "auths.serializers.CustomRegisterSerializer",
    "USER_DETAILS_SERIALIZER":"auths.serializers.CustomUserDetailsSerializer",
    'LOGIN_SERIALIZER': 'dj_rest_auth.serializers.LoginSerializer',
    'TOKEN_MODEL': 'knox.models.AuthToken',
    # "USE_JWT": True,
    # "JWT_AUTH_HTTPONLY": False,  # Makes sure refresh token is sent within response body, not as an httpOnly cookie
    "REST_SESSION_LOGIN": False, # Disable session cookies
        # OLD_PASSWORD_FIELD_ENABLED - set it to True if you want to have old password verification on password change enpoint (default: False)
        # LOGOUT_ON_PASSWORD_CHANGE - set to False if you want to keep the current user logged in after a password change
}


KNOX_TOKEN_MODEL = 'knox.AuthToken'

REST_KNOX = {
#   'SECURE_HASH_ALGORITHM': 'hashlib.sha512',
#   'AUTH_TOKEN_CHARACTER_LENGTH': 64,
#   'TOKEN_TTL': timedelta(hours=10),
  'USER_SERIALIZER': 'knox.serializers.UserSerializer',
  'TOKEN_LIMIT_PER_USER': None,
#   'AUTO_REFRESH': False,
#   'AUTO_REFRESH_MAX_TTL': None,
  'MIN_REFRESH_INTERVAL': 60,
#   'AUTH_HEADER_PREFIX': 'Token',
#   'EXPIRY_DATETIME_FORMAT': api_settings.DATETIME_FORMAT,
  'TOKEN_MODEL': 'knox.AuthToken',
}


# # djangorestframework-simplejwt
# SIMPLE_JWT = {
#     "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
#     "REFRESH_TOKEN_LIFETIME": timedelta(days=2),
#     "ROTATE_REFRESH_TOKENS": True, # when using refreshToken endpoint, both new access and refresh tokens are issued
#     "BLACKLIST_AFTER_ROTATION": True, # when using refreshToken endpoint, the old refresh token is added to blacklist
# }

# EMAIL CONFIG
# using Django SMTP
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER') # email sending address
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')


